/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Healthz */
    get: operations['healthz_healthz_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/window': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Window */
    get: operations['window_api_window_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/headline': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Headline */
    get: operations['headline_api_headline_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/routes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Routes */
    get: operations['routes_api_routes_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/error-distribution': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Error Distribution */
    get: operations['error_distribution_api_error_distribution_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/data-quality': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Data Quality */
    get: operations['data_quality_api_data_quality_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/model-run': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Model Run */
    get: operations['model_run_api_model_run_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stops': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Stops */
    get: operations['stops_api_stops_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stops/{stop_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Stop Detail */
    get: operations['stop_detail_api_stops__stop_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/vehicles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Vehicles */
    get: operations['vehicles_api_vehicles_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/routes/{route_id}/shape': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Route Shape
     * @description One route's geometry only. All shapes together is 192k points.
     */
    get: operations['route_shape_api_routes__route_id__shape_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** CoverageDay */
    CoverageDay: {
      /**
       * Day
       * Format: date
       */
      day: string;
      /** Successful Polls */
      successful_polls: number;
      /** Hours Lost */
      hours_lost: number;
      /** Coverage Pct */
      coverage_pct: number;
    };
    /** DataQuality */
    DataQuality: {
      /** Coverage */
      coverage: components['schemas']['CoverageDay'][];
      /** Label Bands */
      label_bands: components['schemas']['LabelBand'][];
      /** Arrivals Total */
      arrivals_total: number;
      /** Caveats */
      caveats: string[];
    };
    /** DistributionBucket */
    DistributionBucket: {
      /** Source */
      source: string;
      /** Upper Bound Seconds */
      upper_bound_seconds: number;
      /** N */
      n: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** Headline */
    Headline: {
      window: components['schemas']['Window'];
      /** Rows */
      rows: components['schemas']['SourceHorizon'][];
      /**
       * Label Filter Seconds
       * @description Arrivals with a wider ping gap than this are excluded.
       */
      label_filter_seconds: number;
    };
    /** LabelBand */
    LabelBand: {
      /** Band */
      band: string;
      /** N */
      n: number;
      /** Pct */
      pct: number;
    };
    /** ModelRun */
    ModelRun: {
      /**
       * Trained At
       * Format: date-time
       */
      trained_at: string;
      /**
       * Train From
       * Format: date
       */
      train_from: string;
      /**
       * Train To
       * Format: date
       */
      train_to: string;
      /**
       * Test From
       * Format: date
       */
      test_from: string;
      /**
       * Test To
       * Format: date
       */
      test_to: string;
      /** Train Rows */
      train_rows: number | null;
      /** Test Rows */
      test_rows: number | null;
      /** Features */
      features: string[] | null;
      /** Notes */
      notes: string | null;
    };
    /** RouteComparison */
    RouteComparison: {
      /** Route Id */
      route_id: string;
      /** Route Name */
      route_name: string | null;
      /** N */
      n: number;
      /** Mts Mae Seconds */
      mts_mae_seconds: number;
      /** Model Mae Seconds */
      model_mae_seconds: number | null;
      /** Improvement Seconds */
      improvement_seconds: number | null;
    };
    /** RouteShape */
    RouteShape: {
      /** Route Id */
      route_id: string;
      /** Points */
      points: components['schemas']['ShapePoint'][];
    };
    /** ShapePoint */
    ShapePoint: {
      /** Lat */
      lat: number;
      /** Lon */
      lon: number;
    };
    /** SourceHorizon */
    SourceHorizon: {
      /** Source */
      source: string;
      /** Horizon Minutes */
      horizon_minutes: number;
      /** N */
      n: number;
      /** Mae Seconds */
      mae_seconds: number;
      /** Median Seconds */
      median_seconds: number;
      /** P90 Seconds */
      p90_seconds: number;
      /** Bias Seconds */
      bias_seconds: number;
    };
    /** Stop */
    Stop: {
      /** Stop Id */
      stop_id: string;
      /** Stop Name */
      stop_name: string | null;
      /** Lat */
      lat: number;
      /** Lon */
      lon: number;
      /** Arrivals */
      arrivals: number;
    };
    /** StopArrival */
    StopArrival: {
      /** Trip Id */
      trip_id: string;
      /** Route Id */
      route_id: string | null;
      /** Stop Sequence */
      stop_sequence: number;
      /**
       * Arrived At
       * Format: date-time
       */
      arrived_at: string;
      /** Scheduled At */
      scheduled_at: string | null;
      /** Horizon Minutes */
      horizon_minutes: number;
      /** Mts Predicted */
      mts_predicted: string | null;
      /** Model Predicted */
      model_predicted: string | null;
      /** Mts Error Seconds */
      mts_error_seconds: number | null;
      /** Model Error Seconds */
      model_error_seconds: number | null;
    };
    /** StopDetail */
    StopDetail: {
      /** Stop Id */
      stop_id: string;
      /** Stop Name */
      stop_name: string | null;
      /** Recent */
      recent: components['schemas']['StopArrival'][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** Vehicle */
    Vehicle: {
      /** Vehicle Id */
      vehicle_id: string;
      /** Route Id */
      route_id: string | null;
      /** Trip Id */
      trip_id: string | null;
      /** Lat */
      lat: number;
      /** Lon */
      lon: number;
      /**
       * Ts
       * Format: date-time
       */
      ts: string;
    };
    /**
     * Window
     * @description The evaluation window every comparison is computed over.
     */
    Window: {
      /**
       * Test From
       * Format: date
       */
      test_from: string;
      /**
       * Test To
       * Format: date
       */
      test_to: string;
      /** Train From */
      train_from?: string | null;
      /** Train To */
      train_to?: string | null;
      /**
       * Source Of Window
       * @description Where the window came from: the model run, or a fallback.
       */
      source_of_window: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  window_api_window_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Window'];
        };
      };
    };
  };
  headline_api_headline_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Headline'];
        };
      };
    };
  };
  routes_api_routes_get: {
    parameters: {
      query?: {
        /** @description Horizon in minutes */
        horizon?: number;
        /** @description Minimum pairs for a route to appear */
        min_n?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RouteComparison'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  error_distribution_api_error_distribution_get: {
    parameters: {
      query?: {
        /** @description Horizon in minutes */
        horizon?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DistributionBucket'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  data_quality_api_data_quality_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DataQuality'];
        };
      };
    };
  };
  model_run_api_model_run_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ModelRun'] | null;
        };
      };
    };
  };
  stops_api_stops_get: {
    parameters: {
      query?: {
        /** @description Maximum stops returned */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Stop'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  stop_detail_api_stops__stop_id__get: {
    parameters: {
      query?: {
        /** @description Horizon in minutes */
        horizon?: number;
        limit?: number;
      };
      header?: never;
      path: {
        stop_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StopDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  vehicles_api_vehicles_get: {
    parameters: {
      query?: {
        /** @description Ignore stale positions */
        max_age_minutes?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Vehicle'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  route_shape_api_routes__route_id__shape_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        route_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RouteShape'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
